### ISSUE TITLE
Update QuickLink API Password field to use Input Password

### ISSUE THREAD

**Issue by lorenzocaum** [pjsupport/event-espresso4-payjunction-gateway#4]
Hi Matthew, could you update the field for the QuickLink API Password to use password instead of text?

Here is an example:

http://cl.ly/image/1M3H1U3g1r3q

**Comment by pjsupport** [comment]
Hi Lorenzo,

I happily would; I hadn’t found the class for that before and was looking at doing some jQuery to force it as a password field but ran out of time. Unfortunately I can’t get to that link through our firewall. Can you tell me if what the class is called? Is it just EE_Password_Input()?

Best regards,

Matthew E. Cooper
Senior Support Technician
PayJunction <https://www.payjunction.com/> 800.601.0230 x 1132

**Comment by mnelson4** [comment]
@lorenzocaum asked me to chime in.
Ya EE_Password_Input is the one!
FYI they're all defined here: https://github.com/eventespresso/event-espresso-core/tree/master/core/libraries/form_sections/inputs
